apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/component: frontend
spec:
 containers:
 - name: webserver
   image: 750940482526.dkr.ecr.us-east-1.amazonaws.com/hbrar14-docker-assignment:appv1.0
   env:
   - name: DBHOST
     value: 10.96.0.1  # Replace with the hostname of your MySQL service
   - name: DBUSER
     value: root
   - name: DBPWD
     value: password  # Replace with your MySQL password
