---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend

spec:
  containers:
  - name: mysql-db
    image: 750940482526.dkr.ecr.us-east-1.amazonaws.com/hbrar14-docker-assignment:dbv1.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pass123  # Replace with your desired MySQL root password
    - name: MYSQL_DATABASE
      value: employees
    
